name: Auto Merge Bot PRs

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge Lettuce Bot PRs
        id: auto-merge
        uses: lettuce-financial/actions/.github/actions/github/auto-merge@76ac1e062100511893dff34c5a997f0d6a31db30 # 0.47.1
        with:
          app_id: ${{ vars.LETTUCE_BOT_APP_ID }}
          installation_id: ${{ vars.LETTUCE_BOT_INSTALLATION_ID }}
          private_key: ${{ secrets.LETTUCE_BOT_PRIVATE_KEY }}
